---
title: "About"
output: md_document
---

# Thank you for using fplboard!

## fplboard

**fplboard** has been written in R, and is a [Shiny](https://shiny.rstudio.com/) application written as a package using the [golem framework](https://engineering-shiny.org/index.html).

The source code is open and free to re-use. Contributions, code or otherwise, are encouraged!

You can find the Github repository [here](https://github.com/thomaszwagerman/fplboard), or above under the 'Source Code' tab.

This dashboard is built on top of another R package, [fplscrapR](https://github.com/wiscostret/fplscrapR), without which this website would not be possible. Do go and check that out!

## Author

Hi there! My name is Thomas Zwagerman and I'm the author and maintainer of this R package. I am a data scientist and R developer.

Although this is an FPL website I don't work in football/sport. My background is environmental science, and I currently work in local government.

You can find me on [Twitter](https://twitter.com/thomzwa), and I also have a [blog](https://tzwagerman.netlify.app/) with R posts in all sorts of other topics.
