---
title: "Getting Started"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# What is fplboard?
The goal of fplboard is to provide a simple dashboard to visualise FPL's data.

The dashboard has been divided up into three categories:

## **My Team**

Here you can look at the state of your team. How have you performed, and what are your expected points for future gameweeks? Which players with high expected points are not in your team? 

## **Mini-Leagues** 

Examine the state of your mini-league. How has the competition shaped up over the weeks? Who can you slate for having left the most points of the bench, and who has taken the most hits? Spy on your mini-league rivals, are any of them expected to gain more points than you this gameweek?

## **Decision-making Tools** 
Plan your next moves, using realtime FPL data. Who has the kindest fixture runs?

# Getting started with fplboard

To get started with fplboard you'll need a couple of things: the team number of the team you are interested in, and the minileague number of the minileague you're interested in.

### Obtaining Team Number

You'll find your team number in your URL when you navigate to the 'Points' tab on FPL.

### Obtaining League Number

You'll find your minileague number in your URL when you navigate to 'Leagues & Cups', and then select a minileague.

For example, the overall standings' league number is 314.

Happy number crunching!
